import React, { useState, useEffect } from 'react';
import { View, TouchableOpacity, StyleSheet, ScrollView } from 'react-native';
import { Stack, router } from 'expo-router';
import { ThemedText } from '@/components/ThemedText';
import { ThemedView } from '@/components/ThemedView';
import { Ionicons } from '@expo/vector-icons';
import auth from '@react-native-firebase/auth';
import { theme } from '@/styles/theme';
import { OrderService } from '@/services/orders';
import { Order } from '@/app/(dashboard)/customer/types';
